/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/auth/sign-in": {
    /** SIGN-IN */
    post: {
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
  };
  "/api/auth/sign-out": {
    /** SIGN-OUT */
    post: {
      parameters: {
        header?: {
          /** @example Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNscXQzdzlpZTAwMDB0M2NnZGJycnRlYTEiLCJlbWFpbCI6ImFkbWluQGt5cmlvc2Rldi5jb20iLCJpYXQiOjE3MDQwMTQ0NjEsImV4cCI6MTcwNDI3MzY2MX0.mVdZt-VwRLF_E2W5NjIbBCvhwfDNop_7k7WBmHGRgHA */
          Authorization?: string;
        };
      };
      requestBody?: {
        content: {
          "*/*": never;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
  };
  "/api/user/update": {
    /** UPDATE PROFILE */
    put: {
      parameters: {
        header?: {
          /** @example Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNscXQzdzlpZTAwMDB0M2NnZGJycnRlYTEiLCJlbWFpbCI6ImFkbWluQGt5cmlvc2Rldi5jb20iLCJpYXQiOjE3MDQwMTQ0NjEsImV4cCI6MTcwNDI3MzY2MX0.mVdZt-VwRLF_E2W5NjIbBCvhwfDNop_7k7WBmHGRgHA */
          Authorization?: string;
        };
      };
      requestBody?: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
  };
  "/api/media/upload": {
    /** UPLOAD MEDIA */
    post: {
      parameters: {
        header?: {
          /** @example Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNscXQzdzlpZTAwMDB0M2NnZGJycnRlYTEiLCJlbWFpbCI6ImFkbWluQGt5cmlvc2Rldi5jb20iLCJpYXQiOjE3MDQzNzI3MjYsImV4cCI6MTcwNDYzMTkyNn0.YLivCfxxx65a_2FyHSZwyjLjHLyErV5QDmdDCbah55c */
          Authorization?: string;
        };
      };
      requestBody?: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            files?: any;
          };
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
  };
  "/api/site": {
    /** UPLOAD MEDIA */
    post: {
      parameters: {
        header?: {
          /** @example Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNscXQzdzlpZTAwMDB0M2NnZGJycnRlYTEiLCJlbWFpbCI6ImFkbWluQGt5cmlvc2Rldi5jb20iLCJpYXQiOjE3MDQzNzI3MjYsImV4cCI6MTcwNDYzMTkyNn0.YLivCfxxx65a_2FyHSZwyjLjHLyErV5QDmdDCbah55c */
          Authorization?: string;
        };
      };
      requestBody?: {
        content: {
          "*/*": any;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
    put: {
      parameters: {
        header?: {
          /** @example Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImNscXQzdzlpZTAwMDB0M2NnZGJycnRlYTEiLCJlbWFpbCI6ImFkbWluQGt5cmlvc2Rldi5jb20iLCJpYXQiOjE3MDQzNzI3MjYsImV4cCI6MTcwNDYzMTkyNn0.YLivCfxxx65a_2FyHSZwyjLjHLyErV5QDmdDCbah55c */
          Authorization?: string;
        };
      };
      requestBody?: {
        content: {
          "*/*": any;
        };
      };
      responses: {
        /** @description Successful response */
        200: {
          content: {
            "application/json": unknown;
          };
        };
      };
    };
    get: {
      parameters: {
        path: {
          query: any;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
    delete: {
      parameters: {
        path: {
          query: any;
        };
      };
      responses: {
        /** @description Default Response */
        200: {
          content: never;
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export type operations = Record<string, never>;
